### ISSUE TITLE
Exceptions are ignored in A3C tests

### ISSUE THREAD

**Issue by muupan** [chainer/chainerrl#193] opened 2017-12-01 06:51 UTC
Seeing the CI outputs below, exceptions raised in A3C training are currently ignored. The tests should fail instead when exceptions are raised in child processes.

https://travis-ci.org/chainer/chainerrl/jobs/309373685

**Comment by toslunar** [comment] 2018-01-24 09:07
The issue is resolved by #215.

The result of `nosetests -a '!gpu,!slow' tests` of #189 was
```
Ran 3235 tests in 93.009s

OK
```
and after merging the current master the result is
```
======================================================================
FAIL: test_abc_discrete_fast (test_a3c.transplant_class.<locals>.C)  parameter: {'t_max': 1, 'use_lstm': False, 'episodic': False, 'use_bn': True}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tos/Documents/chainerrl/tests/agents_tests/test_a3c.py", line 59, in test_abc_discrete_fast
    episodic=self.episodic, steps=10, require_success=False)
  File "/Users/tos/Documents/chainerrl/tests/agents_tests/test_a3c.py", line 196, in _test_abc
    assert len(warns) == 0, warns[0]
AssertionError: {message : UserWarning('Process #0 (pid=24281) exited with nonzero status 1',), category : 'UserWarning', filename : '/Users/tos/Documents/chainerrl/chainerrl/misc/async.py', lineno : 139, line : None}

======================================================================
FAIL: test_abc_gaussian_fast (test_a3c.transplant_class.<locals>.C)  parameter: {'t_max': 1, 'use_lstm': False, 'episodic': False, 'use_bn': True}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tos/Documents/chainerrl/tests/agents_tests/test_a3c.py", line 70, in test_abc_gaussian_fast
    episodic=self.episodic, steps=10, require_success=False)
  File "/Users/tos/Documents/chainerrl/tests/agents_tests/test_a3c.py", line 196, in _test_abc
    assert len(warns) == 0, warns[0]
AssertionError: {message : UserWarning('Process #0 (pid=24289) exited with nonzero status 1',), category : 'UserWarning', filename : '/Users/tos/Documents/chainerrl/chainerrl/misc/async.py', lineno : 139, line : None}

======================================================================
FAIL: test_abc_fast (test_acer.transplant_class.<locals>.C)  parameter: {'disable_online_update': False, 'discrete': True, 'episodic': False, 'n_times_replay': 0, 't_max': 1, 'use_bn': True, 'use_lstm': False, 'use_trust_region': False}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tos/Documents/chainerrl/tests/agents_tests/test_acer.py", line 372, in test_abc_fast
    steps=10, require_success=False)
  File "/Users/tos/Documents/chainerrl/tests/agents_tests/test_acer.py", line 538, in _test_abc
    assert len(warns) == 0, warns[0]
AssertionError: {message : UserWarning('Process #0 (pid=24563) exited with nonzero status 1',), category : 'UserWarning', filename : '/Users/tos/Documents/chainerrl/chainerrl/misc/async.py', lineno : 139, line : None}

======================================================================
FAIL: test_abc_fast (test_acer.transplant_class.<locals>.C)  parameter: {'disable_online_update': False, 'discrete': False, 'episodic': False, 'n_times_replay': 0, 't_max': 1, 'use_bn': True, 'use_lstm': False, 'use_trust_region': False}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tos/Documents/chainerrl/tests/agents_tests/test_acer.py", line 372, in test_abc_fast
    steps=10, require_success=False)
  File "/Users/tos/Documents/chainerrl/tests/agents_tests/test_acer.py", line 538, in _test_abc
    assert len(warns) == 0, warns[0]
AssertionError: {message : UserWarning('Process #0 (pid=24571) exited with nonzero status 1',), category : 'UserWarning', filename : '/Users/tos/Documents/chainerrl/chainerrl/misc/async.py', lineno : 139, line : None}

----------------------------------------------------------------------
Ran 3242 tests in 92.129s

FAILED (failures=4)
```

**Closed by toslunar** 2018-01-24 09:07 UTC
